
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.2.0
        with:
          from-source: false

      # Runs a single command using the runners shell
      - name: Run make
        run: make
